INSERT INTO PUBLIC.USER (USER_NAME, PASSWORD, ROLE) VALUES ('John', 'password', 'user');
INSERT INTO PUBLIC.USER (USER_NAME, PASSWORD, ROLE) VALUES ('Jinny', 'password', 'user');
INSERT INTO PUBLIC.USER (USER_NAME, PASSWORD, ROLE) VALUES ('Jill', 'password', 'user');
INSERT INTO PUBLIC.USER (USER_NAME, PASSWORD, ROLE) VALUES ('James', 'password', 'user');
INSERT INTO PUBLIC.USER (USER_NAME, PASSWORD, ROLE) VALUES ('Antonio', 'password', 'admin');